#!/bin/bash

# FILES="index.html opensuse.html rtfmindex.html"  # rtfmindex is no longer generated by makeHTML.pl
FILES="index.html opensuse.html"
rsync $FILES -e ssh community.opensuse.org:doc.opensuse.org/htdocs/
